services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  postgres:
    image: postgres:13
    environment:
      - DB_HOST
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
