services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: baggsy
      DB_PASSWORD: baggsy
      DB_NAME: baggsy
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: baggsy
      POSTGRES_PASSWORD: baggsy
      POSTGRES_DB: baggsy
    ports:
      - "5432:5432"
