services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=baggsy
      - POSTGRES_USER=baggsy
      - POSTGRES_PASSWORD=baggsy
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:


# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8080:8080"
#     depends_on:
#       - db
#   frontend:
#     build: ./frontend
#     ports:
#       - "80:80"
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_DB: baggsy
#       POSTGRES_USER: baggsy
#       POSTGRES_PASSWORD: baggsy
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: