version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: baggsy
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
