services:
  baggsy-backend:
    image: vidhij9/baggsy-backend:latest
    environment:
      - PGHOST=${PGHOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_PORT=${DB_PORT}
    ports:
      - "80:80"
