{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.coordinatorlayout",
    "module": "coordinatorlayout",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "coordinatorlayout-1.2.0.aar",
          "url": "coordinatorlayout-1.2.0.aar",
          "size": 43965,
          "sha512": "5e50597cf373b632caf585bd9ad11cbdb0c59a554d12d958209076037b9d6bbca02629c5d1b16c04927734367e7d51962de67b8e4cdbc25caf990adfec890b8d",
          "sha256": "779408b1aa330cd4a7adf1b2e85fd289c30e7edd2e8e42847b7d06589af715fa",
          "sha1": "989c322ce569c805faadafc9e708984a8098fe40",
          "md5": "68f9cc7b53ae46b45613c653cd5ba166"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "coordinatorlayout-1.2.0.aar",
          "url": "coordinatorlayout-1.2.0.aar",
          "size": 43965,
          "sha512": "5e50597cf373b632caf585bd9ad11cbdb0c59a554d12d958209076037b9d6bbca02629c5d1b16c04927734367e7d51962de67b8e4cdbc25caf990adfec890b8d",
          "sha256": "779408b1aa330cd4a7adf1b2e85fd289c30e7edd2e8e42847b7d06589af715fa",
          "sha1": "989c322ce569c805faadafc9e708984a8098fe40",
          "md5": "68f9cc7b53ae46b45613c653cd5ba166"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coordinatorlayout-1.2.0-sources.jar",
          "url": "coordinatorlayout-1.2.0-sources.jar",
          "size": 31033,
          "sha512": "c3ee1e1d51adce8b78a7998d7473fe65681d608aac8a1158d0c98f1d04d18a11176eb70f9a0157c4ee65df4f32a637d2284cdf571c213e6a98ce15db878ad999",
          "sha256": "6fc896e5225cce5a7b62705cf383c52a06e2ccf26d05268968abefd7e3ee9390",
          "sha1": "7a6b816ee556c56cacfa677a6fc98a5fd0e97373",
          "md5": "88ebb99d32cadbce79a19c50e7bf4df2"
        }
      ]
    }
  ]
}
