{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.7.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.7.2.jar",
          "url": "builder-8.7.2.jar",
          "size": 15067552,
          "sha512": "42bb4beb6018105448fcc7c3712d56cb4a8038473f869f17b37a577070362e0d7a86fe7ae099d515ace243490c284062a3c73b4fbee6c31d3e6d130ba995fe38",
          "sha256": "f29f626ce9e41ddfaf305401397a884e5a31126a41fd18f40fdb61ca5461030c",
          "sha1": "d7626a22f7ba2c6e28f4fe718c41f8af90c0a3f0",
          "md5": "4238ccfd687060768a5b3e0f3a32d75a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.7.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.7.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.7.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.7.2"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.7.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.7.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.7.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.7.2.jar",
          "url": "builder-8.7.2.jar",
          "size": 15067552,
          "sha512": "42bb4beb6018105448fcc7c3712d56cb4a8038473f869f17b37a577070362e0d7a86fe7ae099d515ace243490c284062a3c73b4fbee6c31d3e6d130ba995fe38",
          "sha256": "f29f626ce9e41ddfaf305401397a884e5a31126a41fd18f40fdb61ca5461030c",
          "sha1": "d7626a22f7ba2c6e28f4fe718c41f8af90c0a3f0",
          "md5": "4238ccfd687060768a5b3e0f3a32d75a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.7.2-javadoc.jar",
          "url": "builder-8.7.2-javadoc.jar",
          "size": 346021,
          "sha512": "2a2518c4c237a0f68dd78acb54e098fb588054a3bcdc4a6e3816a7ee82da1ec38f73cfaabf49c068cd4b064ad6f72a620a0757fa8c78522f1e3455010718c21b",
          "sha256": "6f47f35d47f0528876f5c1c2cc1f62caf5313582fea359c1ec9158572dcc036b",
          "sha1": "822fd93a003de018ffdd058b87e4aa9a4a28818b",
          "md5": "5843fd23083b01d33efe0c78398d05b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.7.2-sources.jar",
          "url": "builder-8.7.2-sources.jar",
          "size": 282773,
          "sha512": "3f3250c702efd2770323069c660ca85bfa4a0a65257d8f7cf974e5500fc46a1eb44f7b0326f5fb2a211acf0928e22e428390d27a4d0c8dafe19ae5959169fc5e",
          "sha256": "b5666c0dab9a8a3cc09ab00865d75dc7fe1f5e335d408f7ee0a522e56534151f",
          "sha1": "0dd83a22db8039b5bddfc531d49b53b369ef5e59",
          "md5": "b8663dd18808d0f126eb737417c0b0d4"
        }
      ]
    }
  ]
}
