{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-settings-api",
    "version": "8.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.7.2.jar",
          "url": "gradle-settings-api-8.7.2.jar",
          "size": 9836,
          "sha512": "23c152120bc3a6eb75f3b70b0e2d91deae0aaecabafde3a613485e578d5275ec3d80085e68f3c32e2c26f8b071b27d8be4c026eba99b2d8f3c61eed5b315ee23",
          "sha256": "af6a1a17ccdc561be1041edfed136da2dddebaf722bc954e119f2e061a4838d4",
          "sha1": "475ab3f73b86fbd4e057f3c472812d7c06353278",
          "md5": "cc531b0ed3c7d112d3a7d95ef57be999"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-settings-api-8.7.2.jar",
          "url": "gradle-settings-api-8.7.2.jar",
          "size": 9836,
          "sha512": "23c152120bc3a6eb75f3b70b0e2d91deae0aaecabafde3a613485e578d5275ec3d80085e68f3c32e2c26f8b071b27d8be4c026eba99b2d8f3c61eed5b315ee23",
          "sha256": "af6a1a17ccdc561be1041edfed136da2dddebaf722bc954e119f2e061a4838d4",
          "sha1": "475ab3f73b86fbd4e057f3c472812d7c06353278",
          "md5": "cc531b0ed3c7d112d3a7d95ef57be999"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.7.2-javadoc.jar",
          "url": "gradle-settings-api-8.7.2-javadoc.jar",
          "size": 261,
          "sha512": "917d24239e4f9eb0ad5490943844a1a3ba21104f7fbfa849700c41d0b0f408fc3bd1496d970bcbf067e92fb897811719f3f4851f5f3126da4de006331aae9caa",
          "sha256": "1020233050c65f77d8c732f89626ff3d6c341c593e4b00347cf69fe6c0666b31",
          "sha1": "f2a585056c1649eaf272577c063d8b95410e1cdf",
          "md5": "42fcbf00b32f67adec72b60bf8f71d08"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-settings-api-8.7.2-sources.jar",
          "url": "gradle-settings-api-8.7.2-sources.jar",
          "size": 9407,
          "sha512": "8ef0e52b6c12bd04ea60d153d97b7e39ebbc612c09312d71898f87ed223241ad7c0ce0e5700c27e1228244eb93788229b3ce27e41165265cb780a31c68a77253",
          "sha256": "5338dc3547ca73f4d1c03a51fb9235f3a12b782c99b79a28316a3e36e3355a59",
          "sha1": "81447a31dd6ea3a0d441a48a10ce49f6c06839d0",
          "md5": "781fc5a33b1df3644aa18412fc030358"
        }
      ]
    }
  ]
}
